name: Test suite

# Triggers the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: [ sp-addon ]
  pull_request:
    branches: [ sp-addon ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Build job
jobs:
  build:
    name: "${{ matrix.environment.os }} | Blender ${{ matrix.blender.version }}"
    runs-on: ${{ matrix.environment.os }}
    strategy:
      # Do not stop other jobs if one fails
      fail-fast: false
      matrix:
        environment:
        - {
          os: "ubuntu-latest",
          cc: "clang-9",
          cxx: "clang++-9",
          cmake-generator: "Ninja"
        }
        - {
          os: "windows-latest",
          cc: "cl",
          cxx: "cl",
          cmake-generator: "Visual Studio 17 2022"
        }
        blender:
        - {
          version: "2.93.9",
          python: "3.9.2"
        }
        
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: "actions/setup-python@v2"
      with:
        python-version: "${{ matrix.blender.python }}"

    - name: Retrieve Python executable path
      id: python-path
      shell: bash
      run: |
        echo "::set-output name=PYTHON_EXECUTABLE::$(which python)"

    - name: Install Python dependencies
      run: python -m pip install --upgrade requests

    - name: Cache Blender archive
      id: cache-blender
      uses: actions/cache@v3
      with:
        path: blender
        key: ${{ matrix.environment.os }}-${{ matrix.blender.version }}-v1

    - name: Download Blender
      if: steps.cache-blender.outputs.cache-hit != 'true'
      run: python scripts/blender_downloader.py ${{ matrix.blender.version }} -o blender

    - name: Install Blender dependencies
      shell: bash
      run: |
        BLENDER_PYTHON=$(find blender/ -regextype posix-extended -regex '.*bin\/python(.exe|[0-9].[0-9]m?)' -print -quit)
        echo "Blender Python is $BLENDER_PYTHON"
        ./$BLENDER_PYTHON -m ensurepip
        ./$BLENDER_PYTHON -m pip install -U pip
        ./$BLENDER_PYTHON -m pip install --upgrade pytest pytest-cov

    - name: Install Mitsuba build dependencies (Ubuntu)
      if: startsWith(matrix.environment.os, 'ubuntu')
      run: |
        sudo apt install -y clang-9 libc++-9-dev libc++abi-9-dev cmake ninja-build
        sudo apt install -y libz-dev libpng-dev libjpeg-dev libxrandr-dev libxinerama-dev libxcursor-dev
        sudo apt install -y python3-dev python3-distutils python3-setuptools

    - name: Install Mitsuba build dependencies (Windows)
      if: startsWith(matrix.environment.os, 'windows')
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Clone Mitsuba Repository
      uses: actions/checkout@v2
      with:
        repository: ros-dorian/mitsuba3
        ref: xml_to_prop
        path: './mitsuba'
        submodules: recursive
        token: ${{ secrets.MITSUBA_REPO_TOKEN }}

    - name: Retrieve Mitsuba version
      id: mitsuba-version
      shell: bash
      run: |
        pushd mitsuba
        echo "::set-output name=GIT_HEAD_SHA::$(git rev-parse HEAD)"
        popd

    - name: Cache Mitsuba artifacts
      id: cache-mitsuba
      uses: actions/cache@v3
      with:
        path: mitsuba/build
        key: ${{ matrix.environment.os }}-${{ matrix.blender.python }}-${{ steps.mitsuba-version.outputs.GIT_HEAD_SHA }}-v1

    - name: Build Mitsuba
      if: steps.cache-mitsuba.outputs.cache-hit != 'true'
      env:
        CC: ${{ matrix.environment.cc }}
        CXX: ${{ matrix.environment.cxx }}
      shell: bash
      run: |
        pushd mitsuba
        mkdir build
        cmake \
          -S . \
          -B build \
          -G "${{ matrix.environment.cmake-generator }}" \
          -DPython_EXECUTABLE=${{ steps.python-path.outputs.PYTHON_EXECUTABLE }}
        cmake --build build --config Release
        popd

    - name: Run Addon tests (Ubuntu)
      if: startsWith(matrix.environment.os, 'ubuntu')
      shell: bash
      env:
        MITSUBA_DIR: "mitsuba/build/"
      run: |
        ./blender/blender -b --factory-startup --python scripts/run_tests.py -- -v --cov=mitsuba2-blender

    - name: Run Addon tests (Windows)
      if: startsWith(matrix.environment.os, 'windows')
      shell: bash
      env:
        MITSUBA_DIR: "mitsuba/build/Release/"
      run: |
        blender/blender.exe -b --factory-startup --python scripts/run_tests.py -- -v --cov=mitsuba2-blender
