name: Test suite

# Triggers the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: [ sp-addon ]
  pull_request:
    branches: [ sp-addon ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Build job
jobs:
  build:
    name: "${{ matrix.os }} | Blender ${{ matrix.blender.version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      # Do not stop other jobs if one fails
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        blender:
        - {
          version: "2.93.9",
          python: "3.9.2"
        }
        
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: "actions/setup-python@v2"
      with:
        python-version: "${{ matrix.blender.python }}"

    - name: Install Python dependencies
      run: python -m pip install --upgrade requests

    - name: Download Blender
      run: python scripts/blender_downloader.py ${{ matrix.blender.version }} -o blender

    - name: Install Blender dependencies
      run: |
        BLENDER_PYTHON=$(find blender/ -type f -path "*/bin/python*")
        echo "Blender Python is $BLENDER_PYTHON"
        ./$BLENDER_PYTHON -m ensurepip
        ./$BLENDER_PYTHON -m pip install -U pip
        ./$BLENDER_PYTHON -m pip install --upgrade pytest pytest-cov

    - name: Clone Mitsuba Repository
      uses: actions/checkout@v2
      with:
        repository: mitsuba-renderer/mitsuba2
        path: './mitsuba'
        submodules: recursive
        token: ${{ secrets.MITSUBA_REPO_TOKEN }}

    - name: Install Mitsuba build dependencies
      run: |
        sudo apt install -y clang-9 libc++-9-dev libc++abi-9-dev cmake ninja-build
        sudo apt install -y libz-dev libpng-dev libjpeg-dev libxrandr-dev libxinerama-dev libxcursor-dev
        sudo apt install -y python3-dev python3-distutils python3-setuptools

    - name: Build Mitsuba
      run: |
        pushd mitsuba
        export CC=clang-9
        export CXX=clang++-9
        mkdir build
        cd build
        cmake -GNinja ..
        ninja
        popd
